### ISSUE TITLE
Suggestion: Additional Instructions for Colima Configuration on macOS

### ISSUE THREAD

**Issue by sam-hawthorne** [bluedotimpact/bluedot#3]
Hello,

Firstly, thank you for open sourcing your code and the detailed README. I have a small suggestion to improve the container setup instructions for macOS users from my own experience getting the project running locally!

**Suggestion:**

While the current README has Homebrew commands to install Colima, additional configuration may be required, especially if users already have Docker Desktop installed.

**Proposed Addition:**

After the existing Docker instructions for macOS, consider adding a note such as:

---

### Docker on macOS with Colima

For users running Docker containers n macOS, you may need to follow additional configuration steps. Please refer to [this guide](https://smallsharpsoftwaretools.com/tutorials/use-colima-to-run-docker-containers-on-macos/) for more detailed instructions.

---

Thanks for considering - if all looks good I’m happy to fork and open a PR! Hopefully this helps others avoid potential configuration issues :)

**Comment by domdomegg** [comment]
What is in that guide that's not currently in the setup instructions in the README? Running `colima start`? Or uninstalling Docker for Mac? I think without specifying what people should be following in that guide makes it more difficult for people to get set up.

fwiw I think explaining how to use docker / setting up docker compose is probably out of scope for the setup instructions.
