### ISSUE TITLE
[FEATURE REQUEST] Add issue templates

### ISSUE THREAD

**Issue by darigovresearch** [bluedotimpact/bluedot#4]
Having templates would allow for consistency across common types of issues and pull requests along with automatically tagging them as appropriate

The default ones can help with getting enough context and scale up contributions

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests

- [ ] Bug issue template
- [ ] Feature request template

**Comment by domdomegg** [comment]
I think for now this _probably_ overcomplicates things, and increases friction to submitting an issue. If underspecified issues (that could be solved with these templates) do become a problem in future then I think we could look at this in more detail.
